//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCProDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Songs
    {
        public int sid { get; set; }
        public byte[] image { get; set; }
        public string s_name { get; set; }
        public Nullable<System.DateTime> r_date { get; set; }
        public string art_name { get; set; }
        public string genre { get; set; }
        public string album_name { get; set; }
        public string song_link { get; set; }
    }
}
