//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCPro.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlists
    {
        public int Id { get; set; }
        public Nullable<int> Uid { get; set; }
        public string P_name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Sid_arr { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
